//! Render the report directory. The engine owns this directory: it is wiped and
//! regenerated wholesale on every run.

use crate::detect::{Analysis, Breach, Matrix, analyze, breach_by_strike, build_matrix};
use crate::resolver::{Outcome, Step, duel, grind};
use crate::{Character, DamageType};
use std::fmt::Write as _;
use std::io;
use std::path::Path;

/// Cap on trace steps written per one-way grind, to bound slow-grind files.
const MAX_TRACE_STEPS: usize = 200;

/// Wipe and regenerate the whole report directory.
pub fn generate(chars: &[Character], out: &Path) -> io::Result<usize> {
    if out.exists() {
        std::fs::remove_dir_all(out)?;
    }
    let duels = out.join("duels");
    std::fs::create_dir_all(&duels)?;

    let m = build_matrix(chars);
    let a = analyze(&m);

    std::fs::write(out.join("index.md"), render_index(chars, &m, &a))?;
    std::fs::write(out.join("matchups.md"), render_matchups(&m, &a))?;
    std::fs::write(out.join("breach.md"), render_breach(chars, &m))?;
    std::fs::write(out.join("roster.md"), render_roster(chars))?;

    let mut files = 4;
    for i in 0..chars.len() {
        for j in (i + 1)..chars.len() {
            let name = format!("{}-vs-{}.md", chars[i].name, chars[j].name);
            std::fs::write(duels.join(name), render_duel(&chars[i], &chars[j]))?;
            files += 1;
        }
    }
    Ok(files)
}

fn cell(o: Outcome) -> char {
    match o {
        Outcome::Win => 'W',
        Outcome::Loss => 'L',
        Outcome::Draw => '.',
    }
}

fn render_index(chars: &[Character], m: &Matrix, a: &Analysis) -> String {
    let n = chars.len();
    let viable = a.viable();
    let mut s = String::new();

    let _ = writeln!(s, "# Combat report — scorecard\n");
    let _ = writeln!(
        s,
        "Generated by `combat-lab`. Deterministic from the roster + rules. \
         Companion: `matchups.md`, `breach.md`, `roster.md`, `duels/`.\n"
    );

    let _ = writeln!(s, "## Headline\n");
    let _ = writeln!(s, "- **Characters:** {n}");
    let _ = writeln!(s, "- **Viable (non-dominated):** {}", viable.len());
    let _ = writeln!(s, "- **Junk (dominated):** {}", n - viable.len());
    let _ = writeln!(s, "- **Bosses:** {}", count_or_none(&a.bosses, &m.names));
    let _ = writeln!(
        s,
        "- **Doormats:** {}",
        count_or_none(&a.doormats, &m.names)
    );
    let _ = writeln!(
        s,
        "- **Clones:** {}",
        if a.clones.is_empty() {
            "none".to_string()
        } else {
            a.clones
                .iter()
                .map(|&(i, k)| format!("{}≡{}", m.names[i], m.names[k]))
                .collect::<Vec<_>>()
                .join(", ")
        }
    );

    let t = &a.texture;
    let _ = writeln!(
        s,
        "- **Texture:** {} edges · {} walls · {} coin-flips · {} stalemates",
        t.edges, t.walls, t.coinflips, t.stalemates
    );
    let _ = writeln!(s, "- **Immunities (∞ edges):** {}", a.immunities);
    let _ = writeln!(
        s,
        "- **Copeland variance:** {:.2} (0 = perfectly regular)",
        a.copeland_variance
    );
    let _ = writeln!(
        s,
        "- **Nash distance from uniform:** {:.3} (0 = all builds equally played)",
        a.nash_distance
    );

    let _ = writeln!(s, "\n## Structure (strongly-connected components)\n");
    let _ = writeln!(
        s,
        "One big component = a roundtable (good). All singletons = a ladder (boring). \
         Components are listed top tier first.\n"
    );
    for (rank, comp) in a.sccs.iter().enumerate() {
        let names = comp
            .iter()
            .map(|&i| m.names[i].as_str())
            .collect::<Vec<_>>()
            .join(", ");
        let kind = if comp.len() == 1 { "singleton" } else { "tier" };
        let _ = writeln!(s, "{}. ({kind}, {}) {names}", rank + 1, comp.len());
    }

    let _ = writeln!(s, "\n## Per-character verdict\n");
    let _ = writeln!(s, "| Character | W | L | D | Copeland | Nash % | Verdict |");
    let _ = writeln!(s, "|---|--:|--:|--:|--:|--:|---|");
    for i in 0..n {
        let (w, l, d) = a.records[i];
        let verdict = if a.bosses.contains(&i) {
            "BOSS — beats everyone".to_string()
        } else if a.doormats.contains(&i) {
            "DOORMAT — loses to everyone".to_string()
        } else if let Some(k) = a.dominated[i] {
            format!("junk — dominated by {}", m.names[k])
        } else {
            "viable".to_string()
        };
        let _ = writeln!(
            s,
            "| {} | {w} | {l} | {d} | {:+} | {:.0}% | {verdict} |",
            m.names[i],
            a.copeland[i],
            a.nash[i] * 100.0,
        );
    }

    s
}

fn count_or_none(set: &[usize], names: &[String]) -> String {
    if set.is_empty() {
        "none".to_string()
    } else {
        set.iter()
            .map(|&i| names[i].as_str())
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn render_matchups(m: &Matrix, a: &Analysis) -> String {
    let n = m.names.len();
    let mut s = String::new();
    let _ = writeln!(s, "# Matchup matrix (iso-level)\n");
    let _ = writeln!(
        s,
        "Cell = row attacker vs column defender, from the row's view: `W` win, `L` loss, `.` draw.\n"
    );

    let _ = writeln!(s, "## Legend\n");
    for i in 0..n {
        let _ = writeln!(s, "- `{i}` — {}", m.names[i]);
    }

    let _ = write!(s, "\n| vs |");
    for j in 0..n {
        let _ = write!(s, " {j} |");
    }
    let _ = write!(s, "\n|---|");
    for _ in 0..n {
        let _ = write!(s, "--|");
    }
    let _ = writeln!(s);
    for i in 0..n {
        let _ = write!(s, "| **{i}** {} |", m.names[i]);
        for j in 0..n {
            if i == j {
                let _ = write!(s, " — |");
            } else {
                let _ = write!(s, " {} |", cell(m.outcome[i][j]));
            }
        }
        let (w, l, d) = a.records[i];
        let _ = writeln!(s, " {w}/{l}/{d}");
    }

    let _ = writeln!(s, "\n## Per-pair detail\n");
    let _ = writeln!(s, "| A | B | rounds A→B | rounds B→A | winner |");
    let _ = writeln!(s, "|---|---|--:|--:|---|");
    for i in 0..n {
        for j in (i + 1)..n {
            let d = m.duels[i][j].expect("off-diagonal duel");
            let winner = match d.outcome {
                Outcome::Win => m.names[i].as_str(),
                Outcome::Loss => m.names[j].as_str(),
                Outcome::Draw => "draw",
            };
            let _ = writeln!(
                s,
                "| {} | {} | {} | {} | {winner} |",
                m.names[i],
                m.names[j],
                rtk(d.rtk_ab),
                rtk(d.rtk_ba),
            );
        }
    }
    s
}

fn rtk(r: Option<u32>) -> String {
    match r {
        Some(x) => x.to_string(),
        None => "∞".to_string(),
    }
}

fn render_breach(chars: &[Character], m: &Matrix) -> String {
    let n = chars.len();
    let mut s = String::new();
    let _ = writeln!(
        s,
        "# Breach table — how much Might flips a losing matchup\n"
    );
    let _ = writeln!(
        s,
        "For every leg the row does **not** win, the minimum `+Might` it must \
         gain to win. A finite number proves the wall is overcomable by vertical scaling; \
         its size is how god-like you must be.\n"
    );
    let _ = writeln!(s, "| loser | vs | needs +Might |");
    let _ = writeln!(s, "|---|---|--:|");
    for i in 0..n {
        for j in 0..n {
            if i == j || m.outcome[i][j] == Outcome::Win {
                continue;
            }
            let note = match breach_by_strike(&chars[i], &chars[j]) {
                Breach::Already => continue, // already wins (shouldn't hit, guarded above)
                Breach::Needs(d) => format!("+{d}"),
                Breach::Unbounded => format!("> {}", crate::detect::BREACH_MAX),
            };
            let _ = writeln!(s, "| {} | {} | {note} |", m.names[i], m.names[j]);
        }
    }
    s
}

fn render_roster(chars: &[Character]) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "# Roster (as loaded)\n");
    for c in chars {
        let _ = writeln!(s, "## {}\n", c.name);
        let _ = writeln!(s, "```");
        let _ = writeln!(s, "might         {}", c.might);
        let _ = writeln!(s, "weapon        {}", weapon_list(c));
        let _ = writeln!(
            s,
            "vitality      {} × toughness {}",
            c.vitality, c.toughness
        );
        let _ = writeln!(s, "speed         {} actions · daring {}", c.speed, c.daring);
        let _ = writeln!(
            s,
            "resistance    pierce {} slash {} crush {}",
            c.resistance[0], c.resistance[1], c.resistance[2]
        );
        let kw = keyword_list(c);
        if !kw.is_empty() {
            let _ = writeln!(s, "keywords      {kw}");
        }
        let _ = writeln!(s, "```\n");
    }
    s
}

/// The weapon's damage-types, space-joined (a god lists all).
fn weapon_list(c: &Character) -> String {
    c.weapon
        .iter()
        .map(|t| t.name())
        .collect::<Vec<_>>()
        .join(" ")
}

fn channel_name(t: DamageType) -> &'static str {
    match t {
        DamageType::Pierce => "pierce",
        DamageType::Slash => "slash",
        DamageType::Crush => "crush",
    }
}

fn keyword_list(c: &Character) -> String {
    let mut v = Vec::new();
    if c.keywords.persist {
        v.push("persist");
    }
    if c.keywords.cleave {
        v.push("cleave");
    }
    v.join(", ")
}

fn render_duel(a: &Character, b: &Character) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "# {} vs {}\n", a.name, b.name);
    render_one_way(&mut s, a, b);
    render_one_way(&mut s, b, a);

    let d = duel(a, b);
    let verdict = match d.outcome {
        Outcome::Win => format!(
            "**{}** wins — kills in {} vs {}.",
            a.name,
            rtk(d.rtk_ab),
            rtk(d.rtk_ba)
        ),
        Outcome::Loss => format!(
            "**{}** wins — kills in {} vs {}.",
            b.name,
            rtk(d.rtk_ba),
            rtk(d.rtk_ab)
        ),
        Outcome::Draw => "**Draw** — neither closes it out.".to_string(),
    };
    let _ = writeln!(s, "## Verdict\n\n{verdict}");
    s
}

fn render_one_way(s: &mut String, attacker: &Character, defender: &Character) {
    let g = grind(attacker, defender, true);
    let kills = match g.rounds {
        Some(r) => format!("kills in {r} round(s)"),
        None => "never (∞)".to_string(),
    };
    let _ = writeln!(s, "## {} → {}   ({kills})\n", attacker.name, defender.name);

    let toughness = defender.toughness.max(1);

    let _ = writeln!(s, "```");
    let _ = writeln!(
        s,
        "{:9} might-{} {} speed-{} daring-{}{}",
        attacker.name,
        attacker.might,
        weapon_list(attacker),
        attacker.speed,
        attacker.daring,
        keyword_suffix(attacker),
    );
    let _ = writeln!(
        s,
        "{:9} vitality-{} toughness-{} resist-pierce-{} resist-slash-{} resist-crush-{}",
        defender.name,
        defender.vitality,
        toughness,
        defender.resistance[0],
        defender.resistance[1],
        defender.resistance[2],
    );
    let _ = writeln!(s, "{:9} {}", "start", cards_vis(0, defender.vitality));

    let mut shown = 0usize;
    let mut last_round = 0u32;
    for step in &g.steps {
        if shown >= MAX_TRACE_STEPS {
            let _ = writeln!(s, "  … trace truncated");
            break;
        }
        match step {
            Step::Strike(r) => {
                if r.round != last_round {
                    let _ = writeln!(s, "round {}", r.round);
                    last_round = r.round;
                }
                let body = if r.bounced {
                    "bounced — wasted".to_string()
                } else if r.flips == 0 {
                    format!(
                        "acc {}+{}={} / toughness-{toughness}  no flip",
                        r.acc_before, r.damage, r.acc_after
                    )
                } else if r.flips == 1 {
                    let w = if r.waste > 0 {
                        format!(" (waste-{})", r.waste)
                    } else {
                        String::new()
                    };
                    format!(
                        "acc {}+{}={} / toughness-{toughness}  FLIP{w}",
                        r.acc_before,
                        r.damage,
                        r.acc_before + r.damage
                    )
                } else {
                    format!(
                        "acc {}+{}={} / toughness-{toughness}  FLIP×{} (cleave)",
                        r.acc_before,
                        r.damage,
                        r.acc_before + r.damage,
                        r.flips
                    )
                };
                let _ = writeln!(
                    s,
                    "  action {}  {} might-{} − resist-{} = damage-{}   {body}   {}",
                    r.action,
                    channel_name(r.channel),
                    r.might,
                    r.resist,
                    r.damage,
                    cards_vis(r.flipped_total, r.cards_total),
                );
                shown += 1;
            }
            Step::RoundEnd {
                round,
                leftover,
                carried,
            } => {
                let note = if *carried {
                    format!("acc {leftover} carried (persist)")
                } else if *leftover > 0 {
                    format!("acc {leftover} WASTED (round reset)")
                } else {
                    "acc clear".to_string()
                };
                let _ = writeln!(s, "  -- end round {round}: {note}");
                shown += 1;
            }
        }
    }
    if g.rounds.is_none() {
        let _ = writeln!(s, "  -- walled: no path to a kill");
    }
    let _ = writeln!(s, "```\n");
}

/// Render the defender's health as flippable cards: `[#]` flipped, `[ ]` intact.
fn cards_vis(flipped: u32, total: u32) -> String {
    let mut s = String::with_capacity(total as usize * 3);
    for i in 0..total {
        s.push_str(if i < flipped { "[#]" } else { "[ ]" });
    }
    s
}

fn keyword_suffix(c: &Character) -> String {
    let mut v = Vec::new();
    if c.keywords.persist {
        v.push("persist");
    }
    if c.keywords.cleave {
        v.push("cleave");
    }
    if v.is_empty() {
        String::new()
    } else {
        format!(" {}", v.join(" "))
    }
}
